### ISSUE TITLE
Is it possible to make only the progress_background_color behind the stroke color transparent and the rest of the progress_background_color colored?

### ISSUE THREAD

**Issue by sharmanirudh** [emre1512/CircleProgressBar#4]
I want to set the only the background color behind the stroke color transparent and the rest as it is.

Thank you in advance.

**Comment by emre1512** [comment]
I am not sure I understand your question. Can you show an example?

**Comment by sharmanirudh** [comment]
I want something like this.

![web 1920 2](https://user-images.githubusercontent.com/26672724/42990027-203164c8-8c1f-11e8-9171-28fab62dcefe.png)

**Comment by emre1512** [comment]
In the above example, probably the background color is moving/shrinking to achieve the progress effect. You can give transparent colors for background and for progressbar color using my library but I don't think you can achieve something like this, sorry.

**Comment by sharmanirudh** [comment]
I have achieved this thing by a workaround. Thanks for your instant help and for this awesome library.
